### PR TITLE
fsm: restore type-distinguished `ANYTHING_ELSE`

### PR DESCRIPTION
**Pull request by rwe**
In greenery v4, `anything_else` was just an instance of a single-use eponymous class.

In #65, it was changed to a fixed random string to address #64

However, that symbol is _not_ a string: it's a special symbol and has special comparison characteristics. It kinda represents the "co-alphabet".

This re-introduces the class instance, but modernizes it and keeps that original bug fixed.
  * It's made a singleton enum. This allows type-checkers to automatically refine checks like `if x is ANYTHING_ELSE` without needing casts or `isinstance` checks. It also ensures that unplicking does not make a separate instance.
  * The comparison operators are updated to incorporate its special comparison behaviour, eliminating the need to carry an `alphabet_key` helper around.
  * Some tests are added to verify its round-trip pickling behaviour.

### CODE REVIEW

**Comment by qntm** [comment]
This all looks good but please fix the merge conflicts first, then I'll give an approval.

(I feel like there has to be a simpler way to achieve this goal...)

**Comment by rwe** [comment]
> (I feel like there has to be a simpler way to achieve this goal...)

Me too. I'm interesting in trying out [Sapling](https://engineering.fb.com/2022/11/15/open-source/sapling-source-control-scalable/) at some point. GitHub's current UI does not deal with stacked changes too well.

Like, I have the conflicts already resolved, but I have to wait for merges to go in before I can push them up to avoid cluttering the review? Or be forced to rebase, invalidating previous reviews + downstream branches? Grumbug.

**Comment by qntm** [comment]
@rwe OK I tried to fix your merge conflicts myself this time - good job modifying the same code three different ways in parallel - but I'm seeing a ridiculous type error which I think you're better off fixing by yourself. It's saying "Argument 1 to "Charclass" has incompatible type "Set[Union[str, AnythingElse]]"; expected "Union[FrozenSet[str], str]" but I'm guessing it's in error expecting Union[FrozenSet[str], str] because that type doesn't look right at all.

**Comment by rwe** [comment]
@qntm — I have those type errors fixed in future branches. Didn't see the other PR go in, but I have some resolutions ready. Give me just a sec. If you prefer I can just rebase this, too.

**Comment by rwe** [comment]
@qntm There you go. The main conflict was that `alphabet - {ANYTHING_ELSE}` doesn't refine the type the same way as `x is not ANYTHING_ELSE` does, so the resulting set was still `str | AnythingElse`. However you might have seen some type errors related to Charclass, too, since it has some problems.

**Review by qntm — APPROVED** [review]

**Pull request merged**
