### PR TITLE
Transition to setuptools from distutils

### PR DESCRIPTION
**Pull request by pjkundert**
Distutils has poor support for packages arranged with the package source in the root project directory.  Transition to 'setuptools', which supports this without warnings.

### CODE REVIEW

**Comment by ferno** [comment]
Hello pjkundert, some time ago you [added `greenery` to PyPI](https://pypi.python.org/pypi/greenery) and offered to transfer authority to me. Thanks for doing that. I feel like taking control now because there are some changes I want to make. I just created a user account on PyPI, as you suggested. My account name is `ferno`. Can you transfer ownership of the `greenery` package to me, please?

**Comment by pjkundert** [comment]
Sure.  I use it pretty extensively in an industrial communications product
that I have available.  It would be nice if it retained "backwards
compatibility", so that future changes didn't harm people that use my
"cpppo" Python module...

Any chance we can work together to ensure it moves forward smoothly, as far
as compatibility goes?

I will investigate how to proceed with the transfer, hopefully by tomorrow
or the weekend...

Cheers,

--
    -pjk

**Comment by ferno** [comment]
Oh dang, I didn't realise anybody was actually using it. One of the first things I was going to do was rename the `lego` sub-module (if that's the term) to `re`, which makes more sense and is less trademarked. This would probably break whatever you're doing, so maybe I'll not change that right now, although obviously it would be accompanied by a major version bump.

The other major change I had in mind was eliminating the automatic `reduce()` call whenever a `lego` object is changed. I have a feeling this impairs performance in the case of very large inputs.

**Comment by pjkundert** [comment]
OK, I've made 'ferno' an Owner of the greenery package on PiPy...

If you could make sure you roll a major version number when making
potentially incompatible changes, that would be great!

--
    -pjk

**Comment by ferno** [comment]
Thank you!

**Pull request merged**
